[package]
name = "doctrine-migrations-flatten"
version = "0.1.0"
authors = ["Paul Blouët <paul.blouet@ajeel.fr>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
dotenv = "0.13.0"
env_logger = "0.6.0"
log = "0.4.6"
